<script setup lang="ts">
import { defineComponent, ref, reactive, watch } from 'vue'
import { QuestionOutlined, InboxOutlined } from '@ant-design/icons-vue'
import { message } from 'ant-design-vue'
import { Compact } from '@ckpack/vue-color'

import RenderCanvas from './RenderCanvas.vue'

const renderCanvas = ref()

const startRender = () => {
  renderCanvas.value?.startRecording()
}

const cancelRender = () => {
  renderCanvas.value?.stopRecording()
}

const rightPanelTabList = [
  {
    key: 'video',
    tab: 'Video',
  },
  {
    key: 'mask',
    tab: 'Mask',
  },
]
const rightPanelTabKey = ref('video')
const onRightPanelTabChange = (value: string) => {
  console.log("tab change: " + value);
  rightPanelTabKey.value = value

};

const fileList = ref([])

const handleChange = info => {
  if (info.file.status !== 'uploading') {
    // do something
    console.log("uploading")
    console.log(info)
  }
  if (info.file.status === 'done') {
    message.success(`${info.file.name} file opened successfully`)
  } else if (info.file.status === 'error') {
    message.error(`${info.file.name} file open failed.`)
  }
}

const upload = async (file) => {
  // dummy upload function as we don't upload the file
  return true
}

const uploadFiles = ({ onSuccess, onError, file }) => {
  upload(file)
    .then(() => {
      onSuccess(null, file);
    })
    .catch(() => {
      console.log('error');
    })
}


const videoOptions = reactive({
  fps: 30,
  backgroundColor: "black",
  foregroundColor: "white",
})

const updateColor = (color, colorAttribute) => {
  console.log("UC")
  videoOptions[colorAttribute] = color.hex
}

// watch(videoOptions, async (newVideoOptions, oldVideoOptions) => {
//   console.log(newVideoOptions)
// })


</script>


<template>
  <a-layout class="layout">
    <a-layout-header>
      <div class="logo" />
      <a-row type="flex" justify="space-between" align="center">
        <div class="heading">VESC Log Video</div>
        <div>
          <a-col style="line-height: normal; color: white; padding-top: 16px;">
            <a-space direction="vertical" size="12">
              <a-row justify="end">
                <a href="https://github.com/lachlanhurst/vesc-log-video">GitHub repo</a>
              </a-row>
              <a-row justify="end">©2023 Lachlan Hurst</a-row>
            </a-space>
          </a-col>
        </div>
      </a-row>
    </a-layout-header>
    <a-layout-content :style="{ background: '#fff', }">
      <a-row type="flex" :style="{ padding: '8px 8px', height: '100%' }" :gutter="[8, 8]">
        <a-col class="gutter-row" flex="500px" style="height: 100% ; overflow-y: scroll;">
          <div>
            <a-row type="flex" :gutter="[0, 16]">

              <a-card title="Log file" style="width: 100%">
                <a-space direction="vertical" style="width: 100%">
                  <div>Open a CSV log file generated by the VESC Tool.</div>
                  <a-upload-dragger v-model:fileList="fileList" name="file" :multiple="false" :customRequest="uploadFiles"
                    @change="handleChange">
                    <a-row align="middle" justify="center">
                      <a-space>
                        <p class="ant-upload-drag-icon" style="margin-bottom: 0px"><inbox-outlined></inbox-outlined></p>
                        <p class="ant-upload-text">Click or drag file to this area to open</p>
                      </a-space>
                    </a-row>
                  </a-upload-dragger>
                  <a-typography-text type="secondary">
                    Download a sample log file
                    <a href="2023-01-08_17-32-11.csv" download>here</a>.
                  </a-typography-text>
                </a-space>
              </a-card>

              <a-card title="Video details" style="width: 100%">
                <a-form :model="videoOptions" :label-col="{style: {width: '130px'}}" :wrapper-col="{span: 14}">
                  <a-form-item label="Framerate (fps)" class="form-item-less-margin">
                    <a-input-number v-model:value="videoOptions.fps" :min="1" :max="120" />
                  </a-form-item>
                  <a-form-item label="Background color" class="form-item-less-margin">
                    <Compact :modelValue="videoOptions.backgroundColor" class="color-picker" @update:modelValue="updateColor($event, 'backgroundColor')"/>
                  </a-form-item>
                  <a-form-item label="Text color" class="form-item-less-margin">
                    <Compact :modelValue="videoOptions.foregroundColor" class="color-picker" @update:modelValue="updateColor($event, 'foregroundColor')"/>
                  </a-form-item>

                </a-form>


              </a-card>





              <a-card title="Data fields" style="width: 100%">
                <p>Specify which fields in VESC log data will be rendered to video</p>
                <p>card content</p>
                <p v-for="index in 10" :key="index">card content {{ index }}</p>
              </a-card>
            </a-row>
          </div>
        </a-col>
        <a-col class="gutter-row row" flex="auto" style="height: 100%">

          <a-card style="width: 100%" :tab-list="rightPanelTabList" :active-tab-key="rightPanelTabKey" size="small"
            @tabChange="key => onRightPanelTabChange(key)">
            <template #tabBarExtraContent>
              <!-- <a href="#">More</a> -->
              <a-button shape="circle">
                <template #icon>
                  <QuestionOutlined />
                </template>
              </a-button>
            </template>
          </a-card>

          <template v-if="rightPanelTabKey === 'video'">
            <a-row class="flex render-background" align="middle" justify="center">
              <div>
                <RenderCanvas ref="renderCanvas" :videoOptions="videoOptions"/>
              </div>
            </a-row>

            <a-row type="flex" align="middle" :gutter="[8, 8]" style="padding: 8px 0px">
              <a-col class="gutter-row">
                <a-button @click="startRender">
                  Start video render
                </a-button>
              </a-col>
              <a-col class="gutter-row">
                <a-button @click="cancelRender">
                  Cancel
                </a-button>
              </a-col>

              <a-col flex="auto" class="gutter-row">
                <a-progress :percent="50" status="active" />
              </a-col>

            </a-row>

          </template>
          <template v-if="rightPanelTabKey === 'mask'">
            <a-row class="flex render-background" align="middle" justify="center">
              <div>
                mask
              </div>
            </a-row>

            <a-row type="flex" align="middle" :gutter="[8, 8]" style="padding: 8px 0px">
              <a-col class="gutter-row">
                <a-button>
                  Download mask image
                </a-button>
              </a-col>

            </a-row>
          </template>


        </a-col>
      </a-row>
    </a-layout-content>
  </a-layout>
</template>

<style>
.row {
  display: flex;
  flex-direction: column;
  height: 100vh;
}

.flex {
  flex: 1;
}

.heading {
  color: white;
  font-family: Inter, Avenir, Helvetica, Arial, sans-serif;
  font-size: 3.2em;
  font-weight: 400;
}

.site-layout-content {
  min-height: 100%;
  padding: 12px;
  background: #fff;
}

.logo {
  float: left;
  width: 120px;
  height: 31px;
  margin: 16px 24px 16px 0;
  background: rgba(255, 255, 255, 0.3);
}

.ant-row-rtl .logo {
  float: right;
  margin: 16px 0 16px 24px;
}

/* 
[data-theme='dark'] .site-layout-content {
  background: #141414;
} */

.render-background {
  background-image: linear-gradient(rgba(255, 255, 255, .75), rgba(255, 255, 255, .75)), url('../assets/checkered_background.jpg');
}

.color-picker {
  box-shadow: none !important;
  padding: 0px !important;
}

.form-item-less-margin {
  margin-bottom: 12px;
}
</style>