
<script setup lang="ts">
import { defineComponent, ref } from 'vue';

import RenderCanvas from './RenderCanvas.vue'

const renderCanvas = ref()

const startRender = () => {
    renderCanvas.value?.startRecording()
}

const cancelRender = () => {
    renderCanvas.value?.stopRecording()
}

</script>


<template>
  <a-layout class="layout">
    <a-layout-header>
      <div class="logo" />
      <h1>VESC Log Video</h1>
    </a-layout-header>
    <a-layout-content :style="{ background: '#fff',  }">
      <a-row type="flex" :style="{ padding: '8px 8px', height: '100%'  }" :gutter="[8,8]">
        <a-col class="gutter-row" flex="400px">
          <a-row type="flex"  :gutter="[0,16]">
            <!-- <div style="background: red">300px</div> -->

            <a-card title="Log file" size="small" style="width: 100%">
                
                <!-- <template #extra><a href="#">more</a></template> -->
                <p>Upload a CSV log file generated by the VESC Tool</p>
                <p>card content</p>
                <p>card content</p>
            </a-card>

            <a-card title="Video details" size="small" style="width: 100%">
                <p>Frame rate (fps)</p>
                <p>Background color</p>
                <p>Text color</p>
            </a-card>

            <a-card title="Data fields" size="small" style="width: 100%">
            
                <!-- <template #extra><a href="#">more</a></template> -->
                <p>Specify which fields in VESC log data will be rendered to video</p>
                <p>card content</p>
                <p>card content</p>
            </a-card>
          </a-row>
        </a-col>
        <a-col class="gutter-row row" flex="auto" style="height: 100%">

            <a-card title="Video" size="small"> </a-card>
            <a-row class="flex render-background" align="middle" justify="center">
                <!-- style="background: lightgray;" -->
                <div>
                    <RenderCanvas ref="renderCanvas"/>
                </div>
            </a-row>
            

            <a-row type="flex"  align="middle" :gutter="[8,8]" style="padding: 8px 0px">
                <a-col class="gutter-row">
                    <a-button @click="startRender">
                        Start video render
                    </a-button>
                </a-col>
                <a-col class="gutter-row">
                    <a-button @click="cancelRender">
                        Cancel
                    </a-button>
                </a-col>
                
                <a-col flex="auto" class="gutter-row">
                    <a-progress :percent="50" status="active" />
                </a-col>
                
            </a-row>

        </a-col>
      </a-row>
    </a-layout-content>
    <a-layout-footer style="text-align: right; padding: 12px 12px">
      ©2023 Lachlan Hurst - <a href="https://github.com/lachlanhurst/vesc-log-video">GitHub repo</a>
    </a-layout-footer>
  </a-layout>
</template>

<style>
.row {
    display: flex;
    flex-direction: column;
    height: 100vh;
}

.flex {
    flex: 1;
}

h1 {
    color: white;
}

.site-layout-content {
  min-height: 100%;
  padding: 12px;
  background: #fff;
}

.logo {
  float: left;
  width: 120px;
  height: 31px;
  margin: 16px 24px 16px 0;
  background: rgba(255, 255, 255, 0.3);
}

.ant-row-rtl .logo {
  float: right;
  margin: 16px 0 16px 24px;
}
/* 
[data-theme='dark'] .site-layout-content {
  background: #141414;
} */

.render-background {
    background-image: linear-gradient(rgba(255, 255, 255, .75), rgba(255, 255, 255, .75)), url('../assets/checkered_background.jpg');
}
</style>