<script setup lang="ts">

</script>


<template>
  <a-card style="width: 100%">
    <template #title>
      <div class="ant-card-head-title" style="padding-top: 0px; padding-bottom: 0px;">Release notes</div>
      <div class="ant-card-meta-description" style="padding-top: 0px; font-weight: 400; font-size: 14px; margin-top: -8px;">
        What has changed in the latest releases of ESC Log Video
      </div>
    </template>
    <a-list item-layout="vertical" size="small">

      <a-list-item>
        <a-list-item-meta description="" class="meta-class">
          <template #title>
            v0.1.0
          </template>
        </a-list-item-meta>
        <ul class="list-style">
          <li>Initial release. It's all new!</li>
          <li>Support for various log file formats
            <ul>
              <li><a href="https://vesc-project.com/vesc_tool" target="_blank">VESC Tool</a> csv log files as generated by the mobile app
                (Android and iOS)</li>
              <li><a href="https://apps.apple.com/al/app/float-control-vesc-companion/id1590924299?platform=iphone"
                  target="_blank">Float Control</a> log files (iOS)</li>
              <li><a href="https://metr.at/" target="_blank">Metr App</a> (Android and iOS)</li>
            </ul>
            
          </li>
        </ul>
      </a-list-item>

    </a-list>
  </a-card>
</template>


<style scoped>
.meta-class {
  margin-bottom: -12px
}

.list-style {
  padding-left: 16px;
}

ul li {
  list-style-type: "-"
}
</style>